---
configure_fan_profile:
  description: >
    Configure the unit's fan profiles. The unit comes with 4 fixed profiles:
    off/low/medium/high. Each profile is associated with a fan percentage.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: climate.whr_960_ventilation_unit

    profile:
      description: One of 'off', 'low', 'medium' or 'high'. 
      example: low

    percent:
      description: The duty level to set for the profile, expressed in percent. (15-100)
      example: 25
